```{r}
library(tidyverse)
library(tidymodels)
library(dlookr)
tidymodels_prefer()

## Full clean

## GENERAL INFORMATION
train <- read_csv("train.csv")
trainingCoreData =cbind(train["id"], train["percent_dem"], train["total_votes"], train["0001E"])
names(trainingCoreData) = c("Id", "percent_dem", "Votes","Pop")
trainingCoreData = tibble(trainingCoreData)
trainingCoreData$percent_dem = trainingCoreData$percent_dem * 100

## AGE
train <- read_csv("train.csv")
names <- colnames(train)
trainingAge <- train %>%
  mutate(male = .[[5]]/.[[4]]) %>%
  mutate(age0 = .[[36]]/.[[4]]) %>%
  mutate(age20 = .[[17]]/.[[4]]) %>%
  mutate(age25 = .[[19]]/.[[4]]) %>%
  mutate(age35 = .[[21]]/.[[4]]) %>%
  mutate(age45 = .[[23]]/.[[4]]) %>%
  mutate(age55 = .[[25]]/.[[4]]) %>%
  mutate(age60 = .[[27]]/.[[4]]) %>%
  mutate(age65 = .[[29]]/.[[4]]) %>%
  mutate(age75 = .[[31]]/.[[4]]) %>%
  mutate(age85 = .[[33]]/.[[4]]) %>%
  mutate(age18 = 1 - age0 - age20 - age25 - age35 - age45 -
                 age55 - age60 - age65 - age75 - age85) %>%
  select(male, age0, age18, age20, age25, age35,
         age45, age55, age60, age65, age75, age85)

trainingAge = trainingAge*100

## RACE PART 1 
train <- read.csv('train.csv')
train2 <- train[c('X0001E','X0036E','X0037E','X0038E','X0040E','X0041E','X0042E','X0043E','X0039E','X0045E','X0046E','X0047E','X0048E')] 
train2 <- train2 %>% mutate(train2, white = 100 * X0037E / X0001E,
                          black = 100 * X0038E / X0001E,
                          indCher = 100 * X0040E / X0001E,
                          indChip = 100 * X0041E / X0001E,
                          indNava = 100 * X0042E / X0001E,
                          indSiou = 100 * X0043E / X0001E,
                          indOther = 100 * (X0039E - (X0040E + X0041E + X0042E + X0043E)) / X0001E, indian = 100 * X0045E / X0001E,
                          chin = 100 * X0046E / X0001E,
                          fil = 100 * X0047E / X0001E,
                          jap = 100 * X0048E / X0001E)

trainingRacePt1 <- train2[14:24]

## RACE PART 2
train <- read.csv('train.csv')

trainingRacePt2 <- train %>%
  mutate(kor = .[[92]]/.[[4]]) %>%
  mutate(viet = .[[94]]/.[[4]]) %>%
  mutate(asianOther = .[[96]]/.[[4]]) %>%
  mutate(natHawaii = .[[100]]/.[[4]]) %>%
  mutate(natCha = .[[102]]/.[[4]]) %>%
  mutate(natSamoan = .[[104]]/.[[4]]) %>%
  mutate(natOther = .[[106]]/.[[4]]) %>%
  mutate(raceOther = .[[108]]/.[[4]]) %>%
  mutate(twoBlack = .[[112]]/.[[4]]) %>%
  mutate(twoNative = .[[114]]/.[[4]]) %>%
  mutate(twoAsian = .[[116]]/.[[4]]) %>%
  mutate(twoBlackNative = .[[118]]/.[[4]]) %>%
  mutate(twoOther = .[[110]]/.[[4]] - twoBlack - twoNative - twoAsian - twoBlackNative) %>% 
  select(kor, viet, asianOther, natHawaii, natCha, natSamoan,
         natOther, raceOther, twoBlack, twoNative, twoAsian, twoBlackNative, twoOther)

trainingRacePt2 = trainingRacePt2*100
trainingRacePt2

## EDUCATION 
train <- read_csv("train.csv")
TotalPop = train["C01_001E"] + train["C01_006E"]

# % Less than high school graduate
nohighschool = train["C01_002E"]/TotalPop + train["C01_007E"]/TotalPop + train["C01_008E"]/TotalPop

# High school graduate (includes equivalency)
highschool = train["C01_003E"]/TotalPop + train["C01_009E"]/TotalPop

# Some college or associate's degree
somecollege = train["C01_004E"]/TotalPop + train["C01_010E"]/TotalPop + train["C01_011E"]/TotalPop

# Bachelor's degree or higher
bachelorsorhigher = train["C01_005E"]/TotalPop + train["C01_012E"]/TotalPop + train["C01_013E"]/TotalPop

trainingEdu = cbind(nohighschool,highschool,somecollege,bachelorsorhigher)
names(trainingEdu) = c("nohighschool", "highschool", "somecollege", "bachelorsorhigher")
trainingEdu = tibble(trainingEdu)
trainingEdu = trainingEdu*100

finalTrain = tibble(cbind(trainingCoreData, trainingAge, trainingRacePt1, trainingRacePt2, trainingEdu))
round(finalTrain,8)
finalTrain
```

trainNums <- read_csv("ensemble/train.csv") %>%
    select(-ends_with("PE"), -contains("C02")) %>%
    select(Id = id, target = percent_dem, votes = total_votes, pop = "0001E", male = "0002E", female = "0003E", age0 = "0005E", age5 = "0006E", age10 = "0007E", age15 = "0008E", age20 = "0009E", age25 = "0010E", age35 = "0011E", age45 = "0012E", age55 = "0013E", age60 = "0014E", age65 = "0015E", age75 = "0016E", age85 = "0017E", medianAge = "0018E", under18 = "0019E", over16 = "0020E", over18 = "0021E", over21 = "0022E", over62 = "0023E", over65 = "0024E", over18male = "0026E", over18female = "0027E", over65male = "0030E", over65female = "0031E", oneRace = "0034E", twoRace = "0035E", white = "0037E", black = "0038E", native = "0039E", cherokee = "0040E", chippewa = "0041E", navajo = "0042E", sioux = "0043E", asian = "0044E", indian = "0045E", chinese = "0046E", filipino = "0047E", japanese = "0048E", korean = "0049E", viet = "0050E", otherAsian = "0051E", hawaiian = "0052E", hawaiianNative = "0053E", hawaiianChamorro = "0054E", hawaiianSamoan = "0055E", hawaiianOther = "0056E", oneRaceOther = "0057E", twoRacePlus = "0058E", whiteBlack = "0059E", whiteNative = "0060E", whiteAsian = "0061E", blackNative = "0062E", comboWhite = "0064E", comboBlack = "0065E", comboNative = "0066E", comboAsian = "0067E", comboHawaiian = "0068E", comboOther = "0069E", hispanic = "0071E", mexican = "0072E", puertoRican = "0073E", cuban = "0074E", otherHispanic = "0075E", notHispanic = "0076E", notHispanicWhite = "0077E", notHispanicBlack = "0078E", notHispanicNative = "0079E", notHispanicAsian = "0080E", notHispanicHawaiian = "0081E", notHispanicOther = "0082E", notHispanicTwoRace = "0083E", notHispanicTwoRaceSome = "0084E", notHispanicTwoRaceThree = "0085E", housing = "0086E", citizen = "0087E", citizenMale = "0088E", citizenFemale = "0089E", teen = "C01_001E", teenElementary = "C01_002E", teenHigh = "C01_003E", teenCollege = "C01_004E", teenBachelor = "C01_005E", adult = "C01_006E", adultElementary = "C01_007E", adultNoDip = "C01_008E", adultHigh = "C01_009E", adultCollege = "C01_010E", adultAssociate = "C01_011E", adultBachelor = "C01_012E", adultGraduate = "C01_013E", adultHighPlus = "C01_014E", adultBachelorPlus = "C01_015E", twenty = "C01_016E", twentyHighPlus = "C01_017E", twentyBachelorPlus = "C01_018E", thirty = "C01_019E", thirtyHighPlus = "C01_020E", thirtyBachelorPlus = "C01_021E", forty = "C01_022E", fortyHighPlus = "C01_023E", fortyBachelorPlus = "C01_024E", sixty = "C01_025E", sixtyHighPlus = "C01_026E", sixtyBachelorPlus = "C01_027E")
  
testNums <- read_csv("ensemble/test.csv") %>%
    select(-ends_with("PE"), -contains("C02")) %>%
    select(Id = id, target = id, votes = total_votes, pop = "0001E", male = "0002E", female = "0003E", age0 = "0005E", age5 = "0006E", age10 = "0007E", age15 = "0008E", age20 = "0009E", age25 = "0010E", age35 = "0011E", age45 = "0012E", age55 = "0013E", age60 = "0014E", age65 = "0015E", age75 = "0016E", age85 = "0017E", medianAge = "0018E", under18 = "0019E", over16 = "0020E", over18 = "0021E", over21 = "0022E", over62 = "0023E", over65 = "0024E", over18male = "0026E", over18female = "0027E", over65male = "0030E", over65female = "0031E", oneRace = "0034E", twoRace = "0035E", white = "0037E", black = "0038E", native = "0039E", cherokee = "0040E", chippewa = "0041E", navajo = "0042E", sioux = "0043E", asian = "0044E", indian = "0045E", chinese = "0046E", filipino = "0047E", japanese = "0048E", korean = "0049E", viet = "0050E", otherAsian = "0051E", hawaiian = "0052E", hawaiianNative = "0053E", hawaiianChamorro = "0054E", hawaiianSamoan = "0055E", hawaiianOther = "0056E", oneRaceOther = "0057E", twoRacePlus = "0058E", whiteBlack = "0059E", whiteNative = "0060E", whiteAsian = "0061E", blackNative = "0062E", comboWhite = "0064E", comboBlack = "0065E", comboNative = "0066E", comboAsian = "0067E", comboHawaiian = "0068E", comboOther = "0069E", hispanic = "0071E", mexican = "0072E", puertoRican = "0073E", cuban = "0074E", otherHispanic = "0075E", notHispanic = "0076E", notHispanicWhite = "0077E", notHispanicBlack = "0078E", notHispanicNative = "0079E", notHispanicAsian = "0080E", notHispanicHawaiian = "0081E", notHispanicOther = "0082E", notHispanicTwoRace = "0083E", notHispanicTwoRaceSome = "0084E", notHispanicTwoRaceThree = "0085E", housing = "0086E", citizen = "0087E", citizenMale = "0088E", citizenFemale = "0089E", teen = "C01_001E", teenElementary = "C01_002E", teenHigh = "C01_003E", teenCollege = "C01_004E", teenBachelor = "C01_005E", adult = "C01_006E", adultElementary = "C01_007E", adultNoDip = "C01_008E", adultHigh = "C01_009E", adultCollege = "C01_010E", adultAssociate = "C01_011E", adultBachelor = "C01_012E", adultGraduate = "C01_013E", adultHighPlus = "C01_014E", adultBachelorPlus = "C01_015E", twenty = "C01_016E", twentyHighPlus = "C01_017E", twentyBachelorPlus = "C01_018E", thirty = "C01_019E", thirtyHighPlus = "C01_020E", thirtyBachelorPlus = "C01_021E", forty = "C01_022E", fortyHighPlus = "C01_023E", fortyBachelorPlus = "C01_024E", sixty = "C01_025E", sixtyHighPlus = "C01_026E", sixtyBachelorPlus = "C01_027E")

trainPerc <- read_csv("ensemble/train.csv") %>%
    select(Id = id, target = percent_dem, votes = total_votes, pop = "0001E", male = "0002PE", female = "0003PE", age0 = "0005PE", age5 = "0006PE", age10 = "0007PE", age15 = "0008PE", age20 = "0009PE", age25 = "0010PE", age35 = "0011PE", age45 = "0012PE", age55 = "0013PE", age60 = "0014PE", age65 = "0015PE", age75 = "0016PE", age85 = "0017PE", medianAge = "0018E", under18 = "0019PE", over16 = "0020PE", over18 = "0021PE", over21 = "0022PE", over62 = "0023PE", over65 = "0024PE", over18male = "0026PE", over18female = "0027PE", over65male = "0030PE", over65female = "0031PE", oneRace = "0034PE", twoRace = "0035PE", white = "0037PE", black = "0038PE", native = "0039PE", cherokee = "0040PE", chippewa = "0041PE", navajo = "0042PE", sioux = "0043PE", asian = "0044PE", indian = "0045PE", chinese = "0046PE", filipino = "0047PE", japanese = "0048PE", korean = "0049PE", viet = "0050PE", otherAsian = "0051PE", hawaiian = "0052PE", hawaiianNative = "0053PE", hawaiianChamorro = "0054PE", hawaiianSamoan = "0055PE", hawaiianOther = "0056PE", oneRaceOther = "0057PE", twoRacePlus = "0058PE", whiteBlack = "0059PE", whiteNative = "0060PE", whiteAsian = "0061PE", blackNative = "0062PE", comboWhite = "0064PE", comboBlack = "0065PE", comboNative = "0066PE", comboAsian = "0067PE", comboHawaiian = "0068PE", comboOther = "0069PE", hispanic = "0071PE", mexican = "0072PE", puertoRican = "0073PE", cuban = "0074PE", otherHispanic = "0075PE", notHispanic = "0076PE", notHispanicWhite = "0077PE", notHispanicBlack = "0078PE", notHispanicNative = "0079PE", notHispanicAsian = "0080PE", notHispanicHawaiian = "0081PE", notHispanicOther = "0082PE", notHispanicTwoRace = "0083PE", notHispanicTwoRaceSome = "0084PE", notHispanicTwoRaceThree = "0085PE", housing = "0086E", citizen = "0087E", citizenMale = "0088PE", citizenFemale = "0089PE", teenElementary = "C02_002E", teenHigh = "C02_003E", teenCollege = "C02_004E", teenBachelor = "C02_005E", adultElementary = "C02_007E", adultNoDip = "C02_008E", adultHigh = "C02_009E", adultCollege = "C02_010E", adultAssociate = "C02_011E", adultBachelor = "C02_012E", adultGraduate = "C02_013E", adultHighPlus = "C02_014E", adultBachelorPlus = "C02_015E", twentyHighPlus = "C02_017E", twentyBachelorPlus = "C02_018E", thirtyHighPlus = "C02_020E", thirtyBachelorPlus = "C02_021E", fortyHighPlus = "C02_023E", fortyBachelorPlus = "C02_024E", sixtyHighPlus = "C02_026E", sixtyBachelorPlus = "C02_027E")

testPerc <- read_csv("ensemble/test.csv") %>%
    select(Id = id, target = id, votes = total_votes, pop = "0001E", male = "0002PE", female = "0003PE", age0 = "0005PE", age5 = "0006PE", age10 = "0007PE", age15 = "0008PE", age20 = "0009PE", age25 = "0010PE", age35 = "0011PE", age45 = "0012PE", age55 = "0013PE", age60 = "0014PE", age65 = "0015PE", age75 = "0016PE", age85 = "0017PE", medianAge = "0018E", under18 = "0019PE", over16 = "0020PE", over18 = "0021PE", over21 = "0022PE", over62 = "0023PE", over65 = "0024PE", over18male = "0026PE", over18female = "0027PE", over65male = "0030PE", over65female = "0031PE", oneRace = "0034PE", twoRace = "0035PE", white = "0037PE", black = "0038PE", native = "0039PE", cherokee = "0040PE", chippewa = "0041PE", navajo = "0042PE", sioux = "0043PE", asian = "0044PE", indian = "0045PE", chinese = "0046PE", filipino = "0047PE", japanese = "0048PE", korean = "0049PE", viet = "0050PE", otherAsian = "0051PE", hawaiian = "0052PE", hawaiianNative = "0053PE", hawaiianChamorro = "0054PE", hawaiianSamoan = "0055PE", hawaiianOther = "0056PE", oneRaceOther = "0057PE", twoRacePlus = "0058PE", whiteBlack = "0059PE", whiteNative = "0060PE", whiteAsian = "0061PE", blackNative = "0062PE", comboWhite = "0064PE", comboBlack = "0065PE", comboNative = "0066PE", comboAsian = "0067PE", comboHawaiian = "0068PE", comboOther = "0069PE", hispanic = "0071PE", mexican = "0072PE", puertoRican = "0073PE", cuban = "0074PE", otherHispanic = "0075PE", notHispanic = "0076PE", notHispanicWhite = "0077PE", notHispanicBlack = "0078PE", notHispanicNative = "0079PE", notHispanicAsian = "0080PE", notHispanicHawaiian = "0081PE", notHispanicOther = "0082PE", notHispanicTwoRace = "0083PE", notHispanicTwoRaceSome = "0084PE", notHispanicTwoRaceThree = "0085PE", housing = "0086E", citizen = "0087E", citizenMale = "0088PE", citizenFemale = "0089PE", teenElementary = "C02_002E", teenHigh = "C02_003E", teenCollege = "C02_004E", teenBachelor = "C02_005E", adultElementary = "C02_007E", adultNoDip = "C02_008E", adultHigh = "C02_009E", adultCollege = "C02_010E", adultAssociate = "C02_011E", adultBachelor = "C02_012E", adultGraduate = "C02_013E", adultHighPlus = "C02_014E", adultBachelorPlus = "C02_015E", twentyHighPlus = "C02_017E", twentyBachelorPlus = "C02_018E", thirtyHighPlus = "C02_020E", thirtyBachelorPlus = "C02_021E", fortyHighPlus = "C02_023E", fortyBachelorPlus = "C02_024E", sixtyHighPlus = "C02_026E", sixtyBachelorPlus = "C02_027E")
trainPerc <- na.omit(trainPerc)