# July 18th deliverable
#### TRAINING DATASET ####
# % Less than high school graduate
nohighschool = train["C01_002E"]/train["C01_001E"]  + train["C01_007E"]/train["C01_006E"] + train["C01_008E"]/train["C01_006E"]

# High school graduate (includes equivalency)
highschool = train["C01_003E"]/train["C01_001E"] + train["C01_009E"]/train["C01_006E"]

# Some college or associate's degree
somecollege = train["C01_004E"]/train["C01_001E"] + train["C01_010E"]/train["C01_006E"] + train["C01_011E"]/train["C01_006E"]

library(readr)
test <- read_csv("test.csv")
train <- read_csv("train.csv")
column_descriptions <- read_csv("column_descriptions.csv")
sample_submission <- read_csv("sample_submission.csv")

# Bachelor's degree or higher
bachelorsorhigher = train["C01_005E"]/train["C01_001E"] + train["C01_012E"]/train["C01_006E"] + train["C01_013E"]/train["C01_006E"]

trainingEdu = cbind(nohighschool,highschool,somecollege,bachelorsorhigher)
names(trainingEdu) = c("nohighschool", "highschool", "somecollege", "bachelorsorhigher")


#### TEST DATASET ####
# % Less than high school graduate
nohighschool = test["C01_002E"]/test["C01_001E"]  + test["C01_007E"]/test["C01_006E"] + test["C01_008E"]/test["C01_006E"]

# High school graduate (includes equivalency)
highschool = test["C01_003E"]/test["C01_001E"] + test["C01_009E"]/test["C01_006E"]

# Some college or associate's degree
somecollege = test["C01_004E"]/test["C01_001E"] + test["C01_010E"]/test["C01_006E"] + test["C01_011E"]/test["C01_006E"]

# Bachelor's degree or higher
bachelorsorhigher = test["C01_005E"]/test["C01_001E"] + test["C01_012E"]/test["C01_006E"] + test["C01_013E"]/test["C01_006E"]

testEdu = cbind(nohighschool,highschool,somecollege,bachelorsorhigher)
names(testEdu) = c("nohighschool", "highschool", "somecollege", "bachelorsorhigher")

trainingCoreData =cbind(train["id"], train["percent_dem"], train["total_votes"], train["0001E"])
names(trainingCoreData) = c("Id", "percent_dem", "Votes","Pop")

testCoreData = cbind(test["id"], test["total_votes"], test["0001E"])
names(testCoreData) = c("Id", "Votes","Pop")

### FINAL DATAFRAMES TO CONCATONATE ###
trainingEdu
testEdu
trainingCoreData
testCoreData
